import os

#PATH OF THE WEBSITE
WEBSITE_ADDRESS = 'http://127.0.0.1:8000'

#NAME OF THE WEBSITE
WEBSITE_NAME_STR = 'Ayomi'

#SLUG OF THE WEBSITE
WEBSITE_NAME_SLUG = 'Ayomi'

#WEBSITE CAN OPERATE OR NOT
WEBSITE_STATUS = True
