import os

#PATH OF THE WEBSITE
WEBSITE_ADDRESS = 'https://djangoayomi.herokuapp.com'

#NAME OF THE WEBSITE
WEBSITE_NAME_STR = 'Ayomi'

#SLUG OF THE WEBSITE
WEBSITE_NAME_SLUG = 'Ayomi'

#WEBSITE CAN OPERATE OR NOT
WEBSITE_STATUS = True
